### ISSUE TITLE
chore: JPA 설정

### ISSUE THREAD

**Issue by toneofrain** [toneofrain/mytly#3]
## TODO
- [x] JPA 관련 Properties 설정
- [x] JPA Config 작성
- [x] Audit Class 생성
