### ISSUE TITLE
feat: Hard Delete -> Soft Delete

### ISSUE THREAD

**Issue by toneofrain** [toneofrain/mytly#33]
## TODO
- [x] Url status 추가
- [x] Hard Delete -> Soft Delete 변경
- [x] URL 요청시 만료, 삭제 확인 로직 추가
